import React, { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import {
  Modal,
  Button,
  Group,
  Box,
  Text,
  SegmentedControl,
  Menu,
  TextInput,
  Checkbox,
  Stack,
} from "@mantine/core";
import {
  IconPrinter,
  IconX,
  IconFileText,
  IconReceipt,
  IconDownload,
  IconZoomIn,
  IconArrowsMaximize,
  IconBrandWhatsapp,
  IconUser,
  IconBuilding,
  IconShare,
} from "@tabler/icons-react";
import { notifications } from "@mantine/notifications";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMediaQuery } from "@mantine/hooks";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { type Entry } from "../api/entries";
import { type Party, getCompanyPhoneApi, fetchPartiesApi, updatePartyApi } from "../api/parties";
import { formatDate, amountInWordsIndian, formatIndianCurrency } from "../utils/formatters";

interface ChallanPrintModalProps {
  opened: boolean;
  onClose: () => void;
  entry: Entry | null;
  party?: Party | null;
  autoPrint?: boolean;
}

export function formatWhatsAppPhone(phone: string): string {
  const digits = phone.replace(/\D/g, "");
  if (!digits) return "";
  if (digits.length === 10) return `91${digits}`;
  if (digits.length === 11 && digits.startsWith("0")) return `91${digits.slice(1)}`;
  if (digits.length === 12 && digits.startsWith("91")) return digits;
  return digits;
}

function generateChallanWhatsAppText(
  entry: Entry,
  partyDisplayName: string,
  companyPhone: string,
  recipientType: "buyer" | "company"
): string {
  const dateStr = formatDate(entry.created_at || new Date().toISOString());
  const totalFormatted = formatIndianCurrency(entry.total_price);
  const qtyFormatted = Number(entry.quantity).toLocaleString("en-IN", { maximumFractionDigits: 2 });
  const priceFormatted = formatIndianCurrency(entry.unit_price);

  if (recipientType === "company") {
    return `*📦 Delivery Challan Copy - WEST Industries*
━━━━━━━━━━━━━━━━━━━━
📄 *Challan No:* ${entry.challan_no}
📅 *Date:* ${dateStr}
👤 *Buyer / Party:* ${partyDisplayName}
🚛 *Vehicle No:* ${entry.vehicle_no}
📦 *Product:* ${entry.product}
⚖️ *Quantity:* ${qtyFormatted} Pcs @ ${priceFormatted}
💰 *Total Amount:* ${totalFormatted}
📍 *Destination:* ${entry.destination || "N/A"}
━━━━━━━━━━━━━━━━━━━━
_System Record Generated by ChallanGo_`;
  }

  return `*WEST Industries - Delivery Challan*
━━━━━━━━━━━━━━━━━━━━
Hello *${partyDisplayName}*,
Please find your delivery details below:

📄 *Challan No:* ${entry.challan_no}
📅 *Date:* ${dateStr}
🚛 *Vehicle No:* ${entry.vehicle_no}
📦 *Product:* ${entry.product}
⚖️ *Quantity:* ${qtyFormatted} Pcs
💰 *Total Amount:* ${totalFormatted}
📍 *Destination:* ${entry.destination || "N/A"}
━━━━━━━━━━━━━━━━━━━━
For any queries, contact *WEST Industries* at: +91 ${companyPhone || "9034218483"}
Thank you for your business!`;
}

export const ChallanPrintModal: React.FC<ChallanPrintModalProps> = ({
  opened,
  onClose,
  entry,
  party,
  autoPrint = false,
}) => {
  const queryClient = useQueryClient();
  const [printLayout, setPrintLayout] = useState<"full" | "thermal">("full");
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [isSharingWhatsApp, setIsSharingWhatsApp] = useState(false);
  const [phonePromptOpened, setPhonePromptOpened] = useState(false);
  const [customBuyerPhone, setCustomBuyerPhone] = useState("");
  const [savePhoneToParty, setSavePhoneToParty] = useState(true);
  const [phoneError, setPhoneError] = useState<string | null>(null);
  const isMobile = useMediaQuery("(max-width: 48em)");
  const [zoomMode, setZoomMode] = useState<"fit" | "full">("fit");
  const docRef = useRef<HTMLDivElement>(null);
  const [docHeight, setDocHeight] = useState<number>(0);

  useEffect(() => {
    if (docRef.current) {
      setDocHeight(docRef.current.offsetHeight);
    }
  }, [opened, printLayout, entry, zoomMode]);

  // Fetch company phone setting (defaults to WI's 9034218483)
  const { data: companyPhone = "9034218483" } = useQuery({
    queryKey: ["company-phone"],
    queryFn: () => getCompanyPhoneApi(),
    staleTime: 60000,
  });

  // If party prop wasn't passed directly (e.g. from EntriesPage), look it up from catalog
  const { data: allParties = [] } = useQuery({
    queryKey: ["parties-for-print"],
    queryFn: () => fetchPartiesApi(),
    enabled: !party && !!entry?.party_name,
    staleTime: 60000,
  });

  const matchedParty =
    party ||
    (entry?.party_name
      ? allParties.find(
          (p) =>
            (p.trade_name && p.trade_name.toLowerCase() === entry.party_name?.trim().toLowerCase()) ||
            p.name.toLowerCase() === entry.party_name?.trim().toLowerCase()
        )
      : null);

  useEffect(() => {
    if (opened && autoPrint && entry) {
      const timer = setTimeout(() => {
        window.print();
      }, 350);
      return () => clearTimeout(timer);
    }
  }, [opened, autoPrint, entry]);

  if (!entry) return null;

  const handlePrint = () => {
    window.print();
  };

  const formattedDate = formatDate(entry.created_at || new Date().toISOString());
  const hsnCode = "6815"; // Standard for Fly Ash Bricks or building material
  const qty = Number(entry.quantity) || 0;
  const unitPrice = Number(entry.unit_price) || 0;
  const subtotal = Number(entry.subtotal ?? entry.total_price);
  const gstAmount = Number(entry.gst_amount ?? 0);
  const totalPrice = Number(entry.total_price);
  const gstType = entry.gst_type || "none";
  const gstRate = Number(entry.gst_rate) || 0;

  // Party info fallback
  const partyDisplayName = matchedParty?.trade_name || matchedParty?.name || entry.party_name || "-";
  const partyAddress = matchedParty?.address || "-";
  const partyState = matchedParty?.state || "23-Madhya Pradesh";
  const partyGstin = matchedParty?.gst_number || "-";
  const partyPhone = matchedParty?.phone || "";

  // ── Reusable PDF generation helper ──
  const generateChallanPdfBlob = async (): Promise<{ blob: Blob; file: File } | null> => {
    const el = document.getElementById("challan-export-target");
    if (!el) return null;
    const canvas = await html2canvas(el, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
    });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    const blob = pdf.output("blob");
    const file = new File([blob], `Delivery_Challan_${entry.challan_no}.pdf`, {
      type: "application/pdf",
    });
    return { blob, file };
  };

  // ── Download PDF Handler ──
  const handleDownloadPdf = async () => {
    try {
      setIsGeneratingPdf(true);
      const res = await generateChallanPdfBlob();
      if (!res) {
        window.print();
        return;
      }
      const url = URL.createObjectURL(res.blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = res.file.name;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("PDF generation failed:", err);
      window.print();
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // ── WhatsApp Sending Handler ──
  const performSendWhatsApp = async (
    targetPhone: string,
    recipientType: "buyer" | "company"
  ) => {
    try {
      setIsSharingWhatsApp(true);
      const cleanNumber = formatWhatsAppPhone(targetPhone);
      const messageText = generateChallanWhatsAppText(
        entry,
        partyDisplayName,
        companyPhone || "9034218483",
        recipientType
      );

      // Attempt to generate PDF
      let generated: { blob: Blob; file: File } | null = null;
      try {
        generated = await generateChallanPdfBlob();
      } catch (err) {
        console.warn("PDF generation error for WhatsApp share:", err);
      }

      // 1. Check if browser/device supports native file sharing (Android/mobile)
      if (generated && typeof navigator !== "undefined" && navigator.canShare && navigator.canShare({ files: [generated.file] })) {
        await navigator.share({
          title: `Delivery Challan ${entry.challan_no}`,
          text: messageText,
          files: [generated.file],
        });
        notifications.show({
          title: "WhatsApp Share",
          message: "Select WhatsApp to send the attached Challan PDF.",
          color: "green",
          icon: <IconBrandWhatsapp size={18} />,
        });
        return;
      }

      // 2. If file share is not supported by this browser (e.g. desktop),
      // download the PDF and open WhatsApp Web with pre-filled message
      if (generated) {
        const downloadUrl = URL.createObjectURL(generated.blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = generated.file.name;
        a.click();
        URL.revokeObjectURL(downloadUrl);
      }

      const waUrl = cleanNumber
        ? `https://api.whatsapp.com/send?phone=${cleanNumber}&text=${encodeURIComponent(messageText)}`
        : `https://api.whatsapp.com/send?text=${encodeURIComponent(messageText)}`;
      window.open(waUrl, "_blank");

      notifications.show({
        title: "Opening WhatsApp",
        message: cleanNumber
          ? `Opening chat with +${cleanNumber}. PDF downloaded to attach.`
          : "Opening WhatsApp with challan details.",
        color: "green",
        icon: <IconBrandWhatsapp size={18} />,
        autoClose: 5000,
      });
    } catch (err: any) {
      if (err.name !== "AbortError") {
        notifications.show({
          title: "WhatsApp Share Failed",
          message: err?.message || "Could not open WhatsApp.",
          color: "red",
        });
      }
    } finally {
      setIsSharingWhatsApp(false);
    }
  };

  const handleSendToBuyer = () => {
    if (partyPhone && partyPhone.trim()) {
      performSendWhatsApp(partyPhone.trim(), "buyer");
    } else {
      setCustomBuyerPhone("");
      setPhoneError(null);
      setPhonePromptOpened(true);
    }
  };

  const handleConfirmBuyerPhoneSend = async () => {
    const clean = customBuyerPhone.replace(/\D/g, "");
    if (!clean || clean.length < 10) {
      setPhoneError("Please enter a valid 10-digit mobile number");
      return;
    }
    setPhonePromptOpened(false);

    // Save phone to party if checked and party exists
    if (savePhoneToParty && matchedParty?.id) {
      try {
        await updatePartyApi(matchedParty.id, { phone: clean });
        queryClient.invalidateQueries({ queryKey: ["parties"] });
        queryClient.invalidateQueries({ queryKey: ["parties-for-print"] });
      } catch (err) {
        console.error("Could not save phone to party:", err);
      }
    }

    performSendWhatsApp(clean, "buyer");
  };

  const handleSendToCompany = () => {
    performSendWhatsApp(companyPhone || "9034218483", "company");
  };

  const handleGeneralShare = async () => {
    try {
      setIsSharingWhatsApp(true);
      const generated = await generateChallanPdfBlob();
      const messageText = generateChallanWhatsAppText(
        entry,
        partyDisplayName,
        companyPhone || "9034218483",
        "buyer"
      );

      if (generated && typeof navigator !== "undefined" && navigator.canShare && navigator.canShare({ files: [generated.file] })) {
        await navigator.share({
          title: `Delivery Challan ${entry.challan_no}`,
          text: messageText,
          files: [generated.file],
        });
        return;
      }

      if (generated) {
        const downloadUrl = URL.createObjectURL(generated.blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = generated.file.name;
        a.click();
        URL.revokeObjectURL(downloadUrl);
      }

      const waUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(messageText)}`;
      window.open(waUrl, "_blank");
    } catch (err: any) {
      if (err.name !== "AbortError") {
        notifications.show({
          title: "Share Failed",
          message: err?.message || "Could not share.",
          color: "red",
        });
      }
    } finally {
      setIsSharingWhatsApp(false);
    }
  };

  const isThermal = printLayout === "thermal";


  // Reusable Challan Document Component
  const renderChallanDocument = (mode: "full" | "thermal") => {
    const isModeThermal = mode === "thermal";

    return (
      <div
        id={mode === "full" ? "challan-export-target" : undefined}
        className="challan-printable-slip"
        style={{
          width: isModeThermal ? "310px" : "720px",
          minWidth: isModeThermal ? "310px" : "720px",
          maxWidth: isModeThermal ? "310px" : "720px",
          backgroundColor: "#ffffff",
          color: "#000000",
          fontFamily: 'Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
          padding: isModeThermal ? "6px" : "16px 20px",
          boxSizing: "border-box",
          borderRadius: "2px",
          boxShadow: isModeThermal ? "0 0 8px rgba(0,0,0,0.1)" : "0 1px 6px rgba(0,0,0,0.12)",
        }}
      >
        {/* Header Title */}
        <div
          style={{
            textAlign: "center",
            fontSize: isModeThermal ? "14px" : "22px",
            fontWeight: "bold",
            textTransform: "uppercase",
            marginTop: isModeThermal ? "2px" : "8px",
            marginBottom: isModeThermal ? "4px" : "14px",
            letterSpacing: isModeThermal ? "0.5px" : "2px",
            borderBottom: isModeThermal ? "1.5px solid #000" : "2.5px solid #000",
            paddingBottom: isModeThermal ? "2px" : "8px",
          }}
        >
          Delivery Challan
        </div>

        {/* Company Header Box */}
        <div
          style={{
            border: "1.5px solid #000000",
            padding: isModeThermal ? "4px 6px" : "10px 14px",
            boxSizing: "border-box",
          }}
        >
          <div style={{ display: "flex", gap: isModeThermal ? "8px" : "16px", alignItems: "center" }}>
            {/* Trident Logo */}
            <div style={{ flexShrink: 0 }}>
              <svg
                width={isModeThermal ? "30" : "44"}
                height={isModeThermal ? "38" : "56"}
                viewBox="0 0 40 50"
                fill="none"
                stroke="#000"
                strokeWidth={isModeThermal ? "2.5" : "2.8"}
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M20 5v40M20 32c-9 0-14-10-14-22v2M20 32c9 0 14-10 14-22v2M12 45h16" />
              </svg>
            </div>
            <div style={{ flex: 1, fontSize: isModeThermal ? "9.5px" : "12.5px", lineHeight: "1.3" }}>
              <div
                style={{
                  fontSize: isModeThermal ? "13px" : "18px",
                  fontWeight: "bold",
                  letterSpacing: "0.2px",
                }}
              >
                WEST Industries
              </div>
              <div style={{ fontWeight: 500 }}>ASHRAWAD KHURD K NO 39 INDORE INDORE</div>
              <div>Phone: {companyPhone || "9034218483"} &nbsp;|&nbsp; Email: rishi.west@hotmail.com</div>
              <div>
                GSTIN: <strong>23ACAPY4180D1ZS</strong> &nbsp;|&nbsp; State: 23-Madhya Pradesh
              </div>
            </div>
          </div>
        </div>

        {/* Split: Party & Challan Details Box */}
        <div
          style={{
            border: "1.5px solid #000000",
            borderTop: "none",
            display: "flex",
            boxSizing: "border-box",
          }}
        >
          {/* Left Column: Party */}
          <div
            style={{
              flex: "1 1 55%",
              borderRight: "1.5px solid #000",
              padding: isModeThermal ? "4px 6px" : "8px 12px",
              fontSize: isModeThermal ? "9px" : "12px",
              lineHeight: "1.35",
            }}
          >
            <div
              style={{
                fontWeight: "bold",
                fontSize: isModeThermal ? "9.5px" : "13px",
                marginBottom: "3px",
              }}
            >
              Delivery Challan for:
            </div>
            <div
              style={{
                fontWeight: "bold",
                fontSize: isModeThermal ? "10.5px" : "14.5px",
                color: "#000",
              }}
            >
              {partyDisplayName}
            </div>
            {partyPhone ? (
              <div style={{ fontWeight: "bold" }}>
                Phone: {partyPhone}
              </div>
            ) : null}
            <div>{partyAddress}</div>
            <div>State: {partyState}</div>
            <div>GSTIN Number: {partyGstin}</div>
          </div>

          {/* Right Column: Challan Details */}
          <div
            style={{
              flex: "1 1 45%",
              padding: isModeThermal ? "4px 6px" : "8px 12px",
              fontSize: isModeThermal ? "9px" : "12px",
              lineHeight: "1.4",
            }}
          >
            <div
              style={{
                fontWeight: "bold",
                fontSize: isModeThermal ? "9.5px" : "13px",
                marginBottom: "3px",
              }}
            >
              Challan Details:
            </div>
            <div>
              No: <strong style={{ fontSize: isModeThermal ? "11px" : "15px" }}>{entry.challan_no}</strong>
            </div>
            <div>
              Date: <strong>{formattedDate}</strong>
            </div>
          </div>
        </div>

        {/* Transportation Details Box */}
        <div
          style={{
            border: "1.5px solid #000000",
            borderTop: "none",
            padding: isModeThermal ? "4px 6px" : "8px 12px",
            fontSize: isModeThermal ? "9px" : "12px",
            lineHeight: "1.3",
            boxSizing: "border-box",
          }}
        >
          <div
            style={{
              fontWeight: "bold",
              fontSize: isModeThermal ? "9.5px" : "13px",
              marginBottom: "3px",
            }}
          >
            Transportation Details:
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <div>
              Vehicle No.:{" "}
              <strong style={{ fontSize: isModeThermal ? "10.5px" : "14px" }}>{entry.vehicle_no}</strong>
            </div>
            <div>
              Destination: <strong style={{ fontSize: isModeThermal ? "10px" : "13px" }}>{entry.destination || "-"}</strong>
            </div>
          </div>
        </div>

        {/* Items Table */}
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            fontSize: isModeThermal ? "9px" : "12px",
            boxSizing: "border-box",
          }}
        >
          <thead>
            <tr style={{ backgroundColor: "#f2f2f2" }}>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "16px" : "32px" }}>#</th>
              <th style={{ ...thBase(isModeThermal), textAlign: "left" }}>Item name</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "36px" : "60px" }}>HSN/SAC</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "34px" : "55px" }}>Quantity</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "24px" : "45px" }}>Unit</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "42px" : "80px" }}>Price/Unit (₹)</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "46px" : "90px" }}>GST (₹)</th>
              <th style={{ ...thBase(isModeThermal), width: isModeThermal ? "52px" : "105px" }}>Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ ...tdBase(isModeThermal), textAlign: "center" }}>1</td>
              <td style={{ ...tdBase(isModeThermal), fontWeight: "bold" }}>{entry.product}</td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "center" }}>{hsnCode}</td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right", fontWeight: "bold" }}>{qty}</td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "center" }}>Pcs</td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>₹{unitPrice.toFixed(2)}</td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right", fontSize: isModeThermal ? "8px" : "11px" }}>
                {gstType !== "none" ? `₹${gstAmount.toFixed(2)} (${gstRate}%)` : "-"}
              </td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right", fontWeight: "bold" }}>
                ₹{totalPrice.toLocaleString("en-IN", { minimumFractionDigits: 2 })}
              </td>
            </tr>
            {/* Total Row */}
            <tr style={{ fontWeight: "bold", borderTop: "1.5px solid #000" }}>
              <td colSpan={3} style={{ ...tdBase(isModeThermal), textAlign: "left" }}>
                Total
              </td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>{qty}</td>
              <td style={tdBase(isModeThermal)}></td>
              <td style={tdBase(isModeThermal)}></td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right", fontSize: isModeThermal ? "8px" : "11px" }}>
                {gstType !== "none" ? `₹${gstAmount.toFixed(2)}` : "-"}
              </td>
              <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>
                ₹{totalPrice.toLocaleString("en-IN", { minimumFractionDigits: 2 })}
              </td>
            </tr>
          </tbody>
        </table>

        {/* Tax Summary & Totals Box */}
        <div
          style={{
            border: "1.5px solid #000000",
            borderTop: "none",
            padding: isModeThermal ? "4px 6px" : "8px 12px",
            fontSize: isModeThermal ? "9px" : "12px",
            boxSizing: "border-box",
          }}
        >
          {gstType !== "none" && gstRate > 0 && (
            <div style={{ marginBottom: isModeThermal ? "4px" : "8px" }}>
              <div
                style={{
                  fontWeight: "bold",
                  fontSize: isModeThermal ? "9px" : "12.5px",
                  marginBottom: "3px",
                }}
              >
                Tax Summary:
              </div>
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  fontSize: isModeThermal ? "8.5px" : "11.5px",
                  marginBottom: "4px",
                }}
              >
                <thead>
                  <tr style={{ backgroundColor: "#f2f2f2" }}>
                    <th style={thBase(isModeThermal)}>HSN/SAC</th>
                    <th style={thBase(isModeThermal)}>Taxable amount (₹)</th>
                    {gstType === "cgst_sgst" ? (
                      <>
                        <th style={thBase(isModeThermal)}>CGST ({gstRate / 2}%)</th>
                        <th style={thBase(isModeThermal)}>SGST ({gstRate / 2}%)</th>
                      </>
                    ) : (
                      <th style={thBase(isModeThermal)}>IGST ({gstRate}%)</th>
                    )}
                    <th style={thBase(isModeThermal)}>Total Tax (₹)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style={{ ...tdBase(isModeThermal), textAlign: "center" }}>{hsnCode}</td>
                    <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>
                      ₹{subtotal.toLocaleString("en-IN", { minimumFractionDigits: 2 })}
                    </td>
                    {gstType === "cgst_sgst" ? (
                      <>
                        <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>
                          ₹{(gstAmount / 2).toFixed(2)}
                        </td>
                        <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>
                          ₹{(gstAmount / 2).toFixed(2)}
                        </td>
                      </>
                    ) : (
                      <td style={{ ...tdBase(isModeThermal), textAlign: "right" }}>
                        ₹{gstAmount.toFixed(2)}
                      </td>
                    )}
                    <td style={{ ...tdBase(isModeThermal), textAlign: "right", fontWeight: "bold" }}>
                      ₹{gstAmount.toFixed(2)}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          )}

          {/* Sub Total & Grand Total Lines */}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: isModeThermal ? "2px 0" : "3px 0",
              borderTop: "1px dashed #666",
            }}
          >
            <span>Sub Total:</span>
            <span>₹{subtotal.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</span>
          </div>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: isModeThermal ? "2px 0" : "4px 0",
              fontWeight: "bold",
              fontSize: isModeThermal ? "11px" : "15px",
            }}
          >
            <span>Total:</span>
            <span>₹{totalPrice.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</span>
          </div>

          {/* Amount In Words */}
          <div
            style={{
              marginTop: isModeThermal ? "4px" : "6px",
              paddingTop: isModeThermal ? "3px" : "6px",
              borderTop: "1px solid #000",
              fontSize: isModeThermal ? "8.5px" : "12px",
              lineHeight: "1.35",
            }}
          >
            <strong>Delivery Challan Amount In Words:</strong>
            <div style={{ textTransform: "capitalize", marginTop: "1px" }}>
              {amountInWordsIndian(totalPrice)}
            </div>
          </div>
        </div>

        {/* Bank Details & Signature Box */}
        <div
          style={{
            border: "1.5px solid #000000",
            borderTop: "none",
            display: "flex",
            boxSizing: "border-box",
          }}
        >
          {/* Left: Bank Details */}
          <div
            style={{
              flex: "1 1 55%",
              borderRight: "1.5px solid #000",
              padding: isModeThermal ? "4px 6px" : "8px 12px",
              fontSize: isModeThermal ? "8.5px" : "11.5px",
              lineHeight: "1.35",
            }}
          >
            <div style={{ fontWeight: "bold", fontSize: isModeThermal ? "9px" : "12.5px" }}>
              Bank Details:
            </div>
            <div>Name: <strong>ICICI Bank Ltd.</strong></div>
            <div>Account No.: <strong>024105007639</strong></div>
            <div>IFSC code: <strong>ICIC000241</strong></div>
            <div>Account Holder's Name: <strong>WEST Industries</strong></div>
          </div>

          {/* Right: Signature */}
          <div
            style={{
              flex: "1 1 45%",
              padding: isModeThermal ? "4px 6px" : "8px 12px",
              textAlign: "center",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
              fontSize: isModeThermal ? "8.5px" : "11.5px",
            }}
          >
            <div style={{ fontWeight: "bold" }}>For WEST Industries:</div>
            <div style={{ height: isModeThermal ? "26px" : "36px", margin: "4px 0" }}>
              <svg width={isModeThermal ? "60" : "90"} height={isModeThermal ? "24" : "32"} viewBox="0 0 80 30" fill="none" stroke="#222" strokeWidth="1.2">
                <path d="M5 22 C 15 10, 25 28, 35 12 C 45 4, 55 24, 75 18" />
              </svg>
            </div>
            <div style={{ borderTop: "1px solid #000", paddingTop: "3px", fontWeight: "bold" }}>
              Authorized Signatory
            </div>
          </div>
        </div>
      </div>
    );
  };

  const targetWidth = isThermal ? 310 : 720;
  // Available preview width inside modal container on mobile
  const availableWidth = typeof window !== "undefined" ? Math.max(260, window.innerWidth - (isMobile ? 20 : 64)) : 360;
  const shouldScale = isMobile && zoomMode === "fit" && !isThermal;
  const scale = shouldScale ? Math.min(1, availableWidth / targetWidth) : 1;
  const scaledHeight = shouldScale && docHeight > 0 ? Math.ceil(docHeight * scale) + 16 : undefined;

  return (
    <>
      {/* ── Screen Modal Preview ── */}
      <Modal
        opened={opened}
        onClose={onClose}
        fullScreen={isMobile}
        title={
          <Group gap="xs">
            <IconPrinter size={18} />
            <Text fw={700} size="sm">
              Delivery Challan Print Preview
            </Text>
          </Group>
        }
        size={isThermal ? "md" : "xl"}
        centered={!isMobile}
        styles={{
          body: {
            padding: isMobile ? "10px" : "16px",
            backgroundColor: "#181818",
            display: "flex",
            flexDirection: "column",
            maxHeight: isMobile ? "calc(100dvh - 60px)" : undefined,
            overflow: "hidden",
          },
        }}
      >
        {/* Controls: Mode Switcher & Print Button */}
        <Box
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "8px",
            marginBottom: "10px",
            padding: isMobile ? "8px 10px" : "10px 14px",
            backgroundColor: "#262626",
            borderRadius: "6px",
            flexShrink: 0,
          }}
        >
          {/* Top row: Format switcher + Zoom toggle (on mobile) */}
          <Group justify="space-between" align="center" wrap="wrap" gap="xs">
            <SegmentedControl
              value={printLayout}
              onChange={(val) => setPrintLayout(val as "full" | "thermal")}
              size={isMobile ? "xs" : "sm"}
              data={[
                {
                  value: "full",
                  label: (
                    <Group gap={5} align="center" wrap="nowrap">
                      <IconFileText size={14} />
                      <span>{isMobile ? "A4 Standard" : "Full Page (A4 / Standard)"}</span>
                    </Group>
                  ),
                },
                {
                  value: "thermal",
                  label: (
                    <Group gap={5} align="center" wrap="nowrap">
                      <IconReceipt size={14} />
                      <span>{isMobile ? "Thermal (80mm)" : "Thermal Roll (80mm)"}</span>
                    </Group>
                  ),
                },
              ]}
            />

            {isMobile && !isThermal && (
              <Button
                size="xs"
                variant={zoomMode === "fit" ? "light" : "default"}
                color="blue"
                onClick={() => setZoomMode(zoomMode === "fit" ? "full" : "fit")}
                leftSection={zoomMode === "fit" ? <IconZoomIn size={13} /> : <IconArrowsMaximize size={13} />}
              >
                {zoomMode === "fit" ? "100% Zoom" : "Fit Page"}
              </Button>
            )}
          </Group>

          {/* Action buttons row */}
          <Group justify="flex-end" gap="xs" wrap="wrap">
            {/* WhatsApp Share Menu */}
            <Menu shadow="md" width={260} position="bottom-end">
              <Menu.Target>
                <Button
                  leftSection={<IconBrandWhatsapp size={15} />}
                  color="green"
                  size="xs"
                  loading={isSharingWhatsApp}
                >
                  WhatsApp
                </Button>
              </Menu.Target>
              <Menu.Dropdown>
                <Menu.Label>Send Delivery Challan</Menu.Label>
                <Menu.Item
                  leftSection={<IconUser size={15} color="#25D366" />}
                  onClick={handleSendToBuyer}
                >
                  <div>
                    <Text size="xs" fw={600}>Send to Buyer (Customer)</Text>
                    <Text size="10px" c="dimmed">
                      {partyPhone ? `DM: +91 ${partyPhone}` : "Enter Buyer's Phone..."}
                    </Text>
                  </div>
                </Menu.Item>
                <Menu.Item
                  leftSection={<IconBuilding size={15} color="#3B82F6" />}
                  onClick={handleSendToCompany}
                >
                  <div>
                    <Text size="xs" fw={600}>Send to WEST Industries</Text>
                    <Text size="10px" c="dimmed">
                      DM: +91 {companyPhone || "9034218483"}
                    </Text>
                  </div>
                </Menu.Item>
                <Menu.Divider />
                <Menu.Item
                  leftSection={<IconShare size={15} color="#F59E0B" />}
                  onClick={handleGeneralShare}
                >
                  <div>
                    <Text size="xs" fw={600}>Share PDF Document</Text>
                    <Text size="10px" c="dimmed">Attach PDF via Web Share / Any App</Text>
                  </div>
                </Menu.Item>
              </Menu.Dropdown>
            </Menu>

            <Button
              leftSection={<IconDownload size={15} />}
              variant="light"
              color="blue"
              size="xs"
              loading={isGeneratingPdf}
              onClick={handleDownloadPdf}
            >
              Download PDF
            </Button>
            <Button
              leftSection={<IconPrinter size={15} />}
              color="blue"
              size="xs"
              onClick={handlePrint}
            >
              Print Now
            </Button>
            <Button
              variant="default"
              size="xs"
              onClick={onClose}
              leftSection={<IconX size={15} />}
            >
              Close
            </Button>
          </Group>
        </Box>

        {/* ── Scrollable Document Preview ── */}
        <Box
          style={{
            flex: 1,
            maxHeight: isMobile ? "calc(100dvh - 165px)" : "75vh",
            overflowX: shouldScale ? "hidden" : "auto",
            overflowY: "auto",
            WebkitOverflowScrolling: "touch",
            padding: isMobile ? "4px 2px 24px 2px" : "8px 0 16px 0",
            backgroundColor: "#181818",
          }}
        >
          <div
            style={{
              width: shouldScale ? "100%" : `${targetWidth}px`,
              minWidth: shouldScale ? undefined : `${targetWidth}px`,
              height: scaledHeight ? `${scaledHeight}px` : "auto",
              margin: "0 auto",
              display: "flex",
              justifyContent: "center",
              overflow: shouldScale ? "hidden" : "visible",
            }}
          >
            <div
              ref={docRef}
              style={{
                width: `${targetWidth}px`,
                minWidth: `${targetWidth}px`,
                transform: shouldScale ? `scale(${scale})` : "none",
                transformOrigin: "top center",
                flexShrink: 0,
              }}
            >
              {renderChallanDocument(printLayout)}
            </div>
          </div>
        </Box>
      </Modal>

      {/* ── Prompt for Buyer Phone if Missing ── */}
      <Modal
        opened={phonePromptOpened}
        onClose={() => setPhonePromptOpened(false)}
        title={
          <Group gap="xs">
            <IconBrandWhatsapp size={18} color="#25D366" />
            <Text fw={700} size="sm">Send to Buyer via WhatsApp</Text>
          </Group>
        }
        size="sm"
        centered
        zIndex={1100}
      >
        <Stack gap="sm">
          <Text size="xs" c="dimmed">
            No phone number is saved for <strong>{partyDisplayName}</strong>. Enter their 10-digit mobile number to open WhatsApp DM:
          </Text>
          <TextInput
            label="Buyer's Mobile Number"
            placeholder="e.g. 9812345678"
            required
            autoFocus
            leftSection={<Text size="xs" c="dimmed">+91</Text>}
            value={customBuyerPhone}
            onChange={(e) => {
              setCustomBuyerPhone(e.currentTarget.value);
              setPhoneError(null);
            }}
            error={phoneError}
          />
          {matchedParty && (
            <Checkbox
              size="xs"
              label="Save this phone number to Buyer profile"
              checked={savePhoneToParty}
              onChange={(e) => setSavePhoneToParty(e.currentTarget.checked)}
              color="green"
            />
          )}
          <Group justify="flex-end" gap="xs" mt="xs">
            <Button variant="default" size="xs" onClick={() => setPhonePromptOpened(false)}>
              Cancel
            </Button>
            <Button
              color="green"
              size="xs"
              leftSection={<IconBrandWhatsapp size={15} />}
              onClick={handleConfirmBuyerPhoneSend}
            >
              Open WhatsApp
            </Button>
          </Group>
        </Stack>
      </Modal>

      {/* ── Standalone Print Portal for window.print() (Mounted directly to document.body) ── */}
      {typeof document !== "undefined" &&
        createPortal(
          <div id="challan-print-portal" className={`mode-${printLayout}`}>
            {renderChallanDocument(printLayout)}
          </div>,
          document.body
        )}
    </>
  );
};

// ── Reusable cell styles ──
const thBase = (isThermal: boolean): React.CSSProperties => ({
  border: "1.5px solid #000000",
  padding: isThermal ? "3px 2px" : "6px 8px",
  textAlign: "center",
  fontWeight: "bold",
  fontSize: isThermal ? "8.5px" : "11.5px",
});

const tdBase = (isThermal: boolean): React.CSSProperties => ({
  border: "1.5px solid #000000",
  padding: isThermal ? "3px 2px" : "6px 8px",
  fontSize: isThermal ? "8.5px" : "11.5px",
});
