"""create_import_previews_table

Revision ID: 6743a1d01fb4
Revises: 6b67f0231826
Create Date: 2026-09-29 00:26:36.753021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6743a1d01fb4'
down_revision: Union[str, None] = '6b67f0231826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_previews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_previews_expires_at'), 'import_previews', ['expires_at'], unique=False)
    op.create_index(op.f('ix_import_previews_user_id'), 'import_previews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_previews_user_id'), table_name='import_previews')
    op.drop_index(op.f('ix_import_previews_expires_at'), table_name='import_previews')
    op.drop_table('import_previews')
    # ### end Alembic commands ###
