"""update_entry_quantity_numeric_10_2

Revision ID: 6b67f0231826
Revises: 7fe1515b610b
Create Date: 2026-09-29 00:18:58.176056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b67f0231826'
down_revision: Union[str, None] = '7fe1515b610b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
