"""add products table and destination fields to entries

Revision ID: e07794d45bfa
Revises: 6743a1d01fb4
Create Date: 2026-09-29 01:41:10.663554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07794d45bfa'
down_revision: Union[str, None] = '6743a1d01fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index('uq_products_name_lower', 'products', [sa.text('lower(name)')], unique=True)
    op.add_column('entries', sa.Column('destination', sa.String(length=255), server_default='Mumbai', nullable=False))
    op.add_column('entries', sa.Column('destination_lat', sa.Float(), nullable=True))
    op.add_column('entries', sa.Column('destination_lng', sa.Float(), nullable=True))
    op.create_index(op.f('ix_entries_destination'), 'entries', ['destination'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_destination'), table_name='entries')
    op.drop_column('entries', 'destination_lng')
    op.drop_column('entries', 'destination_lat')
    op.drop_column('entries', 'destination')
    op.drop_index('uq_products_name_lower', table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
